// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJ0NEKfIrnEFNALTjcqSL8qw2GEWzbuE',
    appId: '1:828368275074:web:00e0c70028ce7a7477169b',
    messagingSenderId: '828368275074',
    projectId: 'med-smart-e6a0f',
    authDomain: 'med-smart-e6a0f.firebaseapp.com',
    storageBucket: 'med-smart-e6a0f.firebasestorage.app',
    measurementId: 'G-H48T7ZCZLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ygdXjL4CqpIPy1lbQ6q8mN3Gn1Qm-Vk',
    appId: '1:828368275074:android:d196596c12af626777169b',
    messagingSenderId: '828368275074',
    projectId: 'med-smart-e6a0f',
    storageBucket: 'med-smart-e6a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeL7Kd9--jhzNJ2KyOFT9KsYEF8Gzwcno',
    appId: '1:828368275074:ios:873aac8297665d4e77169b',
    messagingSenderId: '828368275074',
    projectId: 'med-smart-e6a0f',
    storageBucket: 'med-smart-e6a0f.firebasestorage.app',
    iosBundleId: 'com.example.medsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeL7Kd9--jhzNJ2KyOFT9KsYEF8Gzwcno',
    appId: '1:828368275074:ios:873aac8297665d4e77169b',
    messagingSenderId: '828368275074',
    projectId: 'med-smart-e6a0f',
    storageBucket: 'med-smart-e6a0f.firebasestorage.app',
    iosBundleId: 'com.example.medsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWJ0NEKfIrnEFNALTjcqSL8qw2GEWzbuE',
    appId: '1:828368275074:web:cbc0d90b2c903a2277169b',
    messagingSenderId: '828368275074',
    projectId: 'med-smart-e6a0f',
    authDomain: 'med-smart-e6a0f.firebaseapp.com',
    storageBucket: 'med-smart-e6a0f.firebasestorage.app',
    measurementId: 'G-12XHS22NRB',
  );
}
